// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"zhangphh/chat_server/internal/middleware"

	"zhangphh/chat_server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{middleware.NewAuthMiddleware(serverCtx.UserCheckClient).Handle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/message",
					Handler: SendMsgHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/conversation/:conversation_id",
					Handler: GetConversationByIdHandler(serverCtx),
				},
			}...,
		),
	)
}
