// Code generated by goctl. DO NOT EDIT.
package types

type SendMsgRequest struct {
	MsgId          string `json:"msg_id"`
	ConversationId string `json:"conversation_id"`
	SendId         uint64 `json:"send_id"`
	ReceiveId      uint64 `json:"receive_id"`
	Content        string `json:"content"`
}

type SendMsgResponse struct {
	MsgId string `json:"msg_id"`
	Code  int32  `json:"code"`
}

type GetConvRequest struct {
	ConversationId string `json:"conversation_id"`
}

type GetConvResponse struct {
	Conversation Conversation `json:"conversation"`
	Code         int32        `json:"code"`
}

type Conversation struct {
	ConversationId string `json:"conversation_id"`
	Users          []User `json:"users"`
	TotalMsgCount  uint64 `json:"total_msg_count"`
	Ctime          uint64 `json:"ctime"`
}

type User struct {
	UserId string `json:"user_id"`
}
